// Mocks generated by Mockito 5.4.6 from annotations
// in petfolio/test/acceptance/share_pet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:petfolio/features/auth/data/auth_service.dart' as _i5;
import 'package:petfolio/features/auth/domain/user.dart' as _i7;
import 'package:petfolio/features/sharing/data/access_token_repository_impl.dart'
    as _i3;
import 'package:petfolio/features/sharing/domain/access_token.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAccessToken_0 extends _i1.SmartFake implements _i2.AccessToken {
  _FakeAccessToken_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccessTokenRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccessTokenRepositoryImpl extends _i1.Mock
    implements _i3.AccessTokenRepositoryImpl {
  MockAccessTokenRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AccessToken> createAccessToken(_i2.AccessToken? token) =>
      (super.noSuchMethod(
            Invocation.method(#createAccessToken, [token]),
            returnValue: _i4.Future<_i2.AccessToken>.value(
              _FakeAccessToken_0(
                this,
                Invocation.method(#createAccessToken, [token]),
              ),
            ),
          )
          as _i4.Future<_i2.AccessToken>);

  @override
  _i4.Future<_i2.AccessToken?> getAccessToken(String? tokenId) =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, [tokenId]),
            returnValue: _i4.Future<_i2.AccessToken?>.value(),
          )
          as _i4.Future<_i2.AccessToken?>);

  @override
  _i4.Future<List<_i2.AccessToken>> getAccessTokensForPet(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#getAccessTokensForPet, [petId]),
            returnValue: _i4.Future<List<_i2.AccessToken>>.value(
              <_i2.AccessToken>[],
            ),
          )
          as _i4.Future<List<_i2.AccessToken>>);

  @override
  _i4.Future<List<_i2.AccessToken>> getAccessTokensByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAccessTokensByUser, [userId]),
            returnValue: _i4.Future<List<_i2.AccessToken>>.value(
              <_i2.AccessToken>[],
            ),
          )
          as _i4.Future<List<_i2.AccessToken>>);

  @override
  _i4.Future<void> updateAccessToken(_i2.AccessToken? token) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccessToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccessToken(String? tokenId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccessToken, [tokenId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deactivateAccessToken(String? tokenId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateAccessToken, [tokenId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.AccessToken>> getExpiredTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredTokens, []),
            returnValue: _i4.Future<List<_i2.AccessToken>>.value(
              <_i2.AccessToken>[],
            ),
          )
          as _i4.Future<List<_i2.AccessToken>>);

  @override
  _i4.Future<void> deleteExpiredTokens() =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpiredTokens, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isTokenValid(String? tokenId) =>
      (super.noSuchMethod(
            Invocation.method(#isTokenValid, [tokenId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.AccessToken?> getTokenByPetAndUser(
    String? petId,
    String? userId,
    _i2.AccessRole? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTokenByPetAndUser, [petId, userId, role]),
            returnValue: _i4.Future<_i2.AccessToken?>.value(),
          )
          as _i4.Future<_i2.AccessToken?>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i6.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i6.User?>.empty(),
          )
          as _i4.Stream<_i6.User?>);

  @override
  _i4.Future<_i7.User?> getCurrentAppUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentAppUser, []),
            returnValue: _i4.Future<_i7.User?>.value(),
          )
          as _i4.Future<_i7.User?>);

  @override
  _i4.Future<_i7.User?> signUpWithEmailAndPassword({
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailAndPassword, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i4.Future<_i7.User?>.value(),
          )
          as _i4.Future<_i7.User?>);

  @override
  _i4.Future<_i7.User?> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i7.User?>.value(),
          )
          as _i4.Future<_i7.User?>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> refreshAndValidateUser() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAndValidateUser, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> updateUserProfile(_i7.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.User?> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i4.Future<_i7.User?>.value(),
          )
          as _i4.Future<_i7.User?>);

  @override
  _i4.Future<Map<String, _i7.User>> getUsersByIds(List<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByIds, [userIds]),
            returnValue: _i4.Future<Map<String, _i7.User>>.value(
              <String, _i7.User>{},
            ),
          )
          as _i4.Future<Map<String, _i7.User>>);
}
