// Mocks generated by Mockito 5.4.6 from annotations
// in petfolio/test/regression/care_plan_regression_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:petfolio/features/care_plans/domain/care_plan.dart' as _i4;
import 'package:petfolio/features/care_plans/domain/care_plan_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CarePlanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarePlanRepository extends _i1.Mock
    implements _i2.CarePlanRepository {
  MockCarePlanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.CarePlan?> watchCarePlanForPet(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCarePlanForPet, [petId]),
            returnValue: _i3.Stream<_i4.CarePlan?>.empty(),
          )
          as _i3.Stream<_i4.CarePlan?>);

  @override
  _i3.Future<_i4.CarePlan?> getCarePlan(String? carePlanId) =>
      (super.noSuchMethod(
            Invocation.method(#getCarePlan, [carePlanId]),
            returnValue: _i3.Future<_i4.CarePlan?>.value(),
          )
          as _i3.Future<_i4.CarePlan?>);

  @override
  _i3.Future<void> createCarePlan(_i4.CarePlan? carePlan) =>
      (super.noSuchMethod(
            Invocation.method(#createCarePlan, [carePlan]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCarePlan(
    String? carePlanId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCarePlan, [carePlanId, updates]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCarePlan(String? carePlanId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCarePlan, [carePlanId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> carePlanExistsForPet(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#carePlanExistsForPet, [petId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
