// Mocks generated by Mockito 5.4.6 from annotations
// in petfolio/test/widget/main_scaffold_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:image_picker/image_picker.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:petfolio/features/auth/data/auth_service.dart' as _i3;
import 'package:petfolio/features/auth/domain/user.dart' as _i6;
import 'package:petfolio/features/care_plans/data/care_plan_repository_impl.dart'
    as _i11;
import 'package:petfolio/features/care_plans/domain/care_plan.dart' as _i12;
import 'package:petfolio/features/pets/data/pets_repository.dart' as _i7;
import 'package:petfolio/features/pets/domain/pet.dart' as _i8;
import 'package:petfolio/features/sharing/data/task_completion_repository_impl.dart'
    as _i13;
import 'package:petfolio/features/sharing/domain/task_completion.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskCompletion_0 extends _i1.SmartFake
    implements _i2.TaskCompletion {
  _FakeTaskCompletion_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i5.User?>.empty(),
          )
          as _i4.Stream<_i5.User?>);

  @override
  _i4.Future<_i6.User?> getCurrentAppUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentAppUser, []),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<_i6.User?> signUpWithEmailAndPassword({
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailAndPassword, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<_i6.User?> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> refreshAndValidateUser() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAndValidateUser, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> updateUserProfile(_i6.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.User?> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<Map<String, _i6.User>> getUsersByIds(List<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByIds, [userIds]),
            returnValue: _i4.Future<Map<String, _i6.User>>.value(
              <String, _i6.User>{},
            ),
          )
          as _i4.Future<Map<String, _i6.User>>);
}

/// A class which mocks [PetsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetsRepository extends _i1.Mock implements _i7.PetsRepository {
  MockPetsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i8.Pet>> watchPetsForOwner(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPetsForOwner, [ownerId]),
            returnValue: _i4.Stream<List<_i8.Pet>>.empty(),
          )
          as _i4.Stream<List<_i8.Pet>>);

  @override
  _i4.Future<void> createPet(_i8.Pet? pet) =>
      (super.noSuchMethod(
            Invocation.method(#createPet, [pet]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePet(String? petId, Map<String, dynamic>? updates) =>
      (super.noSuchMethod(
            Invocation.method(#updatePet, [petId, updates]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePet(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePet, [petId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i8.Pet?> getPetById(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#getPetById, [petId]),
            returnValue: _i4.Future<_i8.Pet?>.value(),
          )
          as _i4.Future<_i8.Pet?>);

  @override
  _i4.Future<String> uploadPetPhoto({
    required String? ownerId,
    required String? petId,
    required _i9.XFile? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPetPhoto, [], {
              #ownerId: ownerId,
              #petId: petId,
              #file: file,
            }),
            returnValue: _i4.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#uploadPetPhoto, [], {
                  #ownerId: ownerId,
                  #petId: petId,
                  #file: file,
                }),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [CarePlanRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarePlanRepositoryImpl extends _i1.Mock
    implements _i11.CarePlanRepositoryImpl {
  MockCarePlanRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i12.CarePlan?> watchCarePlanForPet(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCarePlanForPet, [petId]),
            returnValue: _i4.Stream<_i12.CarePlan?>.empty(),
          )
          as _i4.Stream<_i12.CarePlan?>);

  @override
  _i4.Future<_i12.CarePlan?> getCarePlan(String? carePlanId) =>
      (super.noSuchMethod(
            Invocation.method(#getCarePlan, [carePlanId]),
            returnValue: _i4.Future<_i12.CarePlan?>.value(),
          )
          as _i4.Future<_i12.CarePlan?>);

  @override
  _i4.Future<void> createCarePlan(_i12.CarePlan? carePlan) =>
      (super.noSuchMethod(
            Invocation.method(#createCarePlan, [carePlan]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateCarePlan(
    String? carePlanId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCarePlan, [carePlanId, updates]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCarePlan(String? carePlanId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCarePlan, [carePlanId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> carePlanExistsForPet(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#carePlanExistsForPet, [petId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getCarePlanIdForPet(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#getCarePlanIdForPet, [petId]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}

/// A class which mocks [TaskCompletionRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskCompletionRepositoryImpl extends _i1.Mock
    implements _i13.TaskCompletionRepositoryImpl {
  MockTaskCompletionRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TaskCompletion> createTaskCompletion(
    _i2.TaskCompletion? completion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTaskCompletion, [completion]),
            returnValue: _i4.Future<_i2.TaskCompletion>.value(
              _FakeTaskCompletion_0(
                this,
                Invocation.method(#createTaskCompletion, [completion]),
              ),
            ),
          )
          as _i4.Future<_i2.TaskCompletion>);

  @override
  _i4.Future<_i2.TaskCompletion?> getTaskCompletion(String? completionId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskCompletion, [completionId]),
            returnValue: _i4.Future<_i2.TaskCompletion?>.value(),
          )
          as _i4.Future<_i2.TaskCompletion?>);

  @override
  _i4.Future<List<_i2.TaskCompletion>> getTaskCompletionsForPet(
    String? petId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskCompletionsForPet, [petId]),
            returnValue: _i4.Future<List<_i2.TaskCompletion>>.value(
              <_i2.TaskCompletion>[],
            ),
          )
          as _i4.Future<List<_i2.TaskCompletion>>);

  @override
  _i4.Future<List<_i2.TaskCompletion>> getTaskCompletionsByUser(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskCompletionsByUser, [userId]),
            returnValue: _i4.Future<List<_i2.TaskCompletion>>.value(
              <_i2.TaskCompletion>[],
            ),
          )
          as _i4.Future<List<_i2.TaskCompletion>>);

  @override
  _i4.Future<List<_i2.TaskCompletion>> getTaskCompletionsForTask(
    String? careTaskId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskCompletionsForTask, [careTaskId]),
            returnValue: _i4.Future<List<_i2.TaskCompletion>>.value(
              <_i2.TaskCompletion>[],
            ),
          )
          as _i4.Future<List<_i2.TaskCompletion>>);

  @override
  _i4.Future<void> updateTaskCompletion(_i2.TaskCompletion? completion) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskCompletion, [completion]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTaskCompletion(String? completionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTaskCompletion, [completionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isTaskCompletedByUser(String? careTaskId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#isTaskCompletedByUser, [careTaskId, userId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.TaskCompletion?> getLatestCompletionForTask(
    String? careTaskId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestCompletionForTask, [careTaskId]),
            returnValue: _i4.Future<_i2.TaskCompletion?>.value(),
          )
          as _i4.Future<_i2.TaskCompletion?>);

  @override
  _i4.Stream<List<_i2.TaskCompletion>> watchTaskCompletionsForPet(
    String? petId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchTaskCompletionsForPet, [petId]),
            returnValue: _i4.Stream<List<_i2.TaskCompletion>>.empty(),
          )
          as _i4.Stream<List<_i2.TaskCompletion>>);

  @override
  _i4.Stream<List<_i2.TaskCompletion>> watchTaskCompletionsForTask(
    String? careTaskId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchTaskCompletionsForTask, [careTaskId]),
            returnValue: _i4.Stream<List<_i2.TaskCompletion>>.empty(),
          )
          as _i4.Stream<List<_i2.TaskCompletion>>);

  @override
  _i4.Stream<_i2.TaskCompletion?> watchLatestCompletionForTask(
    String? careTaskId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchLatestCompletionForTask, [careTaskId]),
            returnValue: _i4.Stream<_i2.TaskCompletion?>.empty(),
          )
          as _i4.Stream<_i2.TaskCompletion?>);
}



